meta:
  # Classic favicon formats
  favicon_ico: /favicon/favicon.ico
  favicon_svg: /favicon/favicon.svg
  favicon_96: /favicon/favicon-96x96.png
  favicon_150: /favicon/favicon-150x150.png
  web_am_192: /favicon/web-app-manifest-192x192.png
  web_am_512: /favicon/web-app-manifest-512x512.png

# Progressive web app icons 
manifest: /favicon/manifest.json

# Default Open Graph image
og_image: /images/og/mkm_og_logo.png

# Section Toggles
disable_theme_toggle: false
disable_p2: true
disable_stay_uptodate: true

# Colors
theme_color: "#a2d3db"
background_color: "#ffffff"

# Social Media
social_media:
  linkedin:
    enabled: true
    url: 'https://linkedin.com/in/m-r-miller/'
  github:
    enabled: true
    url: 'https://github.com/mattykakes'
  printables:
    enabled: true
    url: 'https://www.printables.com/@mattykakes_3056026'
  bluesky:
    enabled: true
    url: 'https://bsky.app/profile/mattykakesmakes.com'
  facebook:
    enabled: false
    url: ''
  instagram:
    enabled: false
    url: 'https://instagram.com/matty.kakes.makes/'
  twitter:
    enabled: false
    url: ''

social_franchising:
  buy_me_a_coffee:
    enabled: true
    url: 'https://buymeacoffee.com/mattykakesmakes'
    data_slug: 'mattykakesmakes'

# Index / Home Defaults
author: Matthew Miller
authorimage: images/global/author.webp
description: "Home"
copyright_year: "2025"

welcome:
  heading: "Hi, I'm Matt..."
  subheading: "...and this is Matty Kakes Makes!"
  Subheading_short: "...and this is"
  description: "The digital garage where code meets chaos, CAD meets caffeine, and half-baked ideas somehow turn into working(ish) projects."

p1:
  heading: "What you'll find here..."
  image: "images/pages/matt_garage_idk2_2025.webp"
  image_quality: 78
  image_width: 600
  content:
    - text: "Building things is my primary creative outlet. It’s a way to think laterally about solving problems — sometimes by creating something highly functional, and other times, something delightfully absurd. Every build is an opportunity to experiment, learn, and translate an idea into a tangible result."
    - text: "Engineering Projects - From software to hardware, this is where code, circuits, and machines collide. Expect projects that range from practical tools to strange experiments that maybe shouldn’t work… but somehow do."
    - text: "Technical Blogs - Deep dives, lessons learned, and professional opinions. These posts are equal parts documentation, storytelling, and lessons learn from both personal and professional experiences."
    - text: "Creative Builds - This is where ideas take a playful detour. Some projects are practical, others are purely for fun, and a few land somewhere in between."

p2:
  heading: Why "Matty Kakes"?
  image: images/pages/mkm_broken_cake_1.png
  image_quality: 45
  image_width: 600
  content:
    - text: "Moved to the about page LOL"

p3:
    heading: "Recent Posts"
    content:
      - text: "The latest things I’ve been building, thinking, and writing about!"
